### ISSUE TITLE
Can't update Craft CMS to 3.8

### ISSUE THREAD

**Issue by maxpdesign** [masugadesign/lab-reports-craft-cms#2]
Hi,

A client website is running on Craft CMS version 3.7.68 and also has Lab Reports version 1.0.0 installed. When I try updating to Craft CMS 3.8.0, I get an error because Lab Reports expects a version below 3.8.0.

Does Lab Reports not support this version or can this version restriction be removed?

**Comment by benjaminkohl** [comment]
We just released Lab Reports v1.0.1 which will now support all versions of Craft 3.6 - 3.*.

**Comment by benjaminkohl** [comment]
Closing this one since Lab Reports v1.0.1 supports Craft 3.8.
