### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by josh-attwood** [masugadesign/lab-reports-craft-cms#6]
We are having an issue with memory, we are getting the following error:

```
Allowed memory size of 268435456 bytes exhausted (tried to allocate 266240 bytes)
```

We have a php memory limit of 512mb so can't work out why this would still be throwing an error.

**Comment by MattAppleton** [comment]
Actually — memory limit on the install:

`The memory_limit directive in php.ini is currently set to 1024M.`

**Comment by benjaminkohl** [comment]
I suspect you are running a _Basic_ type report on a very large data set. About how many rows are you anticipating in the results? If there are thousands of rows and/or numerous columns that require loading relationships, I'd suggest switching to an _Advanced_ report type which can paginate through the query results. The trouble with Basic reports is that they have to load all the results upfront.

[Here is more info on setting up advanced reports.](https://github.com/masugadesign/lab-reports-craft-cms#advanced-reports)

If you aren't expecting a large number of rows then maybe there is an issue in your report template. I could take a look at it and see if I spot anything.

**Comment by MattAppleton** [comment]
When it does work — it randomly generated a file earlier, though usually it fails — the .csv is pretty large, which could be an issue — 3.7Mb, 11k rows, so hopefully well within capabilities of the plugin...

We are making a 'basic' report

**Comment by MattAppleton** [comment]
@benjaminkohl  — sounds like we need to try an Advanced report then... will try...

**Comment by benjaminkohl** [comment]
Yeah, 11,000 rows is a lot for Craft to load into memory at once. I suggest switching to an advanced report which is much better at memory management because of the fact that it can paginate through the query results.

**Comment by josh-attwood** [comment]
Just implemented as an advanced report and is working nice and smoothly, thanks @benjaminkohl

**Comment by MattAppleton** [comment]
thanks @benjaminkohl  :)

**Comment by benjaminkohl** [comment]
@josh-attwood @MattAppleton I am glad that is working for you! Advanced reports are definitely the way to go with larger amounts of data.
